version: '3.8'

services:
  ai-cfo-web:
    build: .
    container_name: ai-cfo-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_N8N_WEBHOOK_URL=http://localhost:5678/webhook/process-financials
    restart: unless-stopped
    networks:
      - ai-cfo-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Local n8n instance - no authentication required
  ai-cfo-n8n:
    image: n8nio/n8n:latest
    container_name: ai-cfo-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_METRICS=false
      - N8N_EDITOR_BASE_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n-financial-workflow.json:/import/workflow.json:ro
    restart: unless-stopped
    networks:
      - ai-cfo-network

networks:
  ai-cfo-network:
    driver: bridge

volumes:
  n8n_data:
    driver: local
