version: '3.8'

services:
  ai-cfo-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai-cfo-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_N8N_WEBHOOK_URL=http://n8n:5678/webhook/process-financials
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - ai-cfo-network
    depends_on:
      - n8n

  n8n:
    image: n8nio/n8n:latest
    container_name: ai-cfo-n8n-dev
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=development
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data_dev:/home/node/.n8n
      - ./n8n-financial-workflow.json:/import/workflow.json:ro
    restart: unless-stopped
    networks:
      - ai-cfo-network

networks:
  ai-cfo-network:
    driver: bridge

volumes:
  n8n_data_dev:
    driver: local
